---
name: cf-subway

instance_groups:
- name: subway
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: subway-broker
    release: cf-subway
    consumes:
      servicebroker:
        from: servicebroker
        deployment: docker-broker

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: cf-subway
  version: 3.0.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/cf-subway-boshrelease?v=3.0.0
  sha1: 4e241dff1552e626e0677941da69944eafeca1ff
