---
name: cf-subway

instance_groups:
- name: subway
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: subway-broker
    release: cf-subway
    consumes:
      backend:
        from: ((backend-broker))
        deployment: ((backend-deployment))
    provides:
      subway:
        as: broker
        shared: true
    properties:
      username: broker
      password: ((subway-broker-password))
      name: ((subway-broker-name))

variables:
- name: subway-broker-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: cf-subway
  version: 3.2.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/cf-subway-boshrelease?v=3.2.0
  sha1: 57de13d5a7b4709c065b6f909cd86372badfe2da
