meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: subway-broker
    templates:
    - name: subway-broker
      release: cf-subway
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties:
  subway_broker:
    backend_brokers: (( merge ))
    backends: (( merge ))
    username: (( merge ))
    password: (( merge ))
